/** Run with `bun run generate:icons` after changing ResearchMark. */
import { createHash } from "node:crypto";
import { mkdir, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { format } from "prettier";
import { renderToStaticMarkup } from "react-dom/server";
import sharp from "sharp";

import { ResearchMark } from "../src/components/brand/research-mark";

const root = fileURLToPath(new URL("../", import.meta.url));
const svg = renderToStaticMarkup(<ResearchMark size={512} />);
const revision = createHash("sha256").update(svg).digest("hex").slice(0, 12);
const prefix = `/brand/research-mark-${revision}`;
await mkdir(`${root}public/brand`, { recursive: true });
await writeFile(`${root}public${prefix}.svg`, svg);
for (const size of [32, 180, 192, 512]) {
  await sharp(Buffer.from(svg))
    .resize(size, size)
    .png()
    .toFile(`${root}public${prefix}-${size}.png`);
}

// A maskable icon keeps the mark inside the platform's safe area.
const maskable = renderToStaticMarkup(
  <svg xmlns="http://www.w3.org/2000/svg" width="512" height="512">
    <rect width="512" height="512" fill="#0D2421" />
    <g transform="translate(77,77)">
      <ResearchMark size={358} />
    </g>
  </svg>,
);
await sharp(Buffer.from(maskable)).png().toFile(`${root}public${prefix}-maskable.png`);

// ICO containers can hold PNG images; include native sizes for older browsers.
const sizes = [16, 32, 48];
const frames = await Promise.all(
  sizes.map((size) => sharp(Buffer.from(svg)).resize(size, size).png().toBuffer()),
);
const directory = Buffer.alloc(6 + 16 * frames.length);
directory.writeUInt16LE(1, 2);
directory.writeUInt16LE(frames.length, 4);
let offset = directory.length;
frames.forEach((frame, index) => {
  const entry = 6 + index * 16;
  directory[entry] = sizes[index]!;
  directory[entry + 1] = sizes[index]!;
  directory.writeUInt16LE(1, entry + 4);
  directory.writeUInt16LE(32, entry + 6);
  directory.writeUInt32LE(frame.length, entry + 8);
  directory.writeUInt32LE(offset, entry + 12);
  offset += frame.length;
});
const ico = Buffer.concat([directory, ...frames]);
await writeFile(`${root}public${prefix}.ico`, ico);
await writeFile(`${root}public/favicon.ico`, ico);
await writeFile(
  `${root}src/lib/brand-assets.ts`,
  await format(
    `// Generated by scripts/generate-icons.tsx from ResearchMark; do not edit URLs by hand.\n` +
      `export const BRAND_ASSETS = ${JSON.stringify(
        {
          svg: `${prefix}.svg`,
          favicon: `${prefix}.ico`,
          png32: `${prefix}-32.png`,
          apple: `${prefix}-180.png`,
          png192: `${prefix}-192.png`,
          png512: `${prefix}-512.png`,
          maskable: `${prefix}-maskable.png`,
        },
        null,
        2,
      )} as const;\n`,
    { parser: "typescript" },
  ),
);
console.log(`Generated Research Agent icons: ${revision}`);
