// Generated by scripts/generate-icons.tsx from ResearchMark; do not edit URLs by hand.
export const BRAND_ASSETS = {
  svg: "/brand/research-mark-98e91ec9822b.svg",
  favicon: "/brand/research-mark-98e91ec9822b.ico",
  png32: "/brand/research-mark-98e91ec9822b-32.png",
  apple: "/brand/research-mark-98e91ec9822b-180.png",
  png192: "/brand/research-mark-98e91ec9822b-192.png",
  png512: "/brand/research-mark-98e91ec9822b-512.png",
  maskable: "/brand/research-mark-98e91ec9822b-maskable.png",
} as const;
