// Generated by scripts/generate-icons.tsx from ResearchMark; do not edit URLs by hand.
export const BRAND_ASSETS = {
  svg: "/brand/research-mark-c486c223f411.svg",
  favicon: "/brand/research-mark-c486c223f411.ico",
  png32: "/brand/research-mark-c486c223f411-32.png",
  apple: "/brand/research-mark-c486c223f411-180.png",
  png192: "/brand/research-mark-c486c223f411-192.png",
  png512: "/brand/research-mark-c486c223f411-512.png",
  maskable: "/brand/research-mark-c486c223f411-maskable.png",
} as const;
